version: 2.0.{build}
branches:
  only:
  - dev
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    nuget restore BackToTheFutureV.sln
build:
  project: BackToTheFutureV.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a BackToTheFutureV.zip %APPVEYOR_BUILD_FOLDER%\BackToTheFutureV\bin\Release\*

    7z a KlangRageAudioLibrary.zip %APPVEYOR_BUILD_FOLDER%\KlangRageAudioLibrary\bin\Release\*

    appveyor PushArtifact BackToTheFutureV.zip

    appveyor PushArtifact KlangRageAudioLibrary.zip
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
